# Installed Gems
plugins: [
  jekyll-sitemap,
  jekyll-mentions,
  jekyll-paginate
]

# Site settings
title: Java Server Faces
email: info@javaserverfaces.com
description: > # this means to ignore newlines until "baseurl:"
  JavaServer Faces - Rich Application Platform, Community Portal, Resource Center
baseurl: ''
# url: 'http://dev.javaserverfaces.com'
url: 'https://jsf-site.github.io/jsf-site/'
twitter_username: ''
github_username: jsf-site

# Build settings
markdown: kramdown

paginate: 3
paginate_path: 'news/page:num'